import logging

from dotenv import load_dotenv
from typing import TypedDict, List, Optional, Callable
from pydantic import BaseModel, Field

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.messages import ToolMessage, ToolCall, AIMessage
from langgraph.graph import StateGraph, END
from langgraph.graph.state import CompiledStateGraph
from langgraph.prebuilt import ToolNode

from prompts.agent import get_planning_prompt_template, get_execution_prompt_template
from config.config import (
    DEFAULT_MODEL, MODEL_TEMPERATURE, MODEL_TOP_P, MAX_COMPLETION_TOKENS,
    LOG_FORMAT, LOG_DATE_FORMAT, LOG_LEVEL
)
from toolbox import (
    textual_entity_search, textual_retrieval_augment
)

# Load environment variables
load_dotenv()

# Configure logging
logging.basicConfig(
    level=getattr(logging, LOG_LEVEL),
    format=LOG_FORMAT,
    datefmt=LOG_DATE_FORMAT
)
logger = logging.getLogger(__name__)


# Structured output models for LLM responses
class PlanningOutput(BaseModel):
    """Structured output for tool chain planning."""
    known_info: List[str] = Field(description="List of information items that are directly provided or known from the query")
    tool_chain: List[str] = Field(description="Ordered list of tools needed to answer the query")


# Define the state structure for the agent
class AgentState(TypedDict):
    """State structure for the planning agent."""
    user_query: str # The user's soccer-related question
    additional_material: Optional[str] # Additional material (e.g, image/video related to the user question)
    known_info: List[str] # This is generated by the planning step: Information known or provided directly. This is generated by the planning step.
    tool_chain: List[str] # This is generated by the planning step: The planned sequence of tools to execute. 
    tool_calls_history: List[ToolCall] # History of tool calls (requests to call a tool)
    tool_results_history: List[ToolMessage] # History of tool results (results of tool executions)
    tool_node_messages: Optional[List] # Messages exchanged between execution_node and tool_node
    last_tool_artifact: Optional[str] # To store the tool's artifact output from the last tool call


class SoccerAgent:
    """
    A LangGraph-based agent for planning soccer knowledge queries.
    
    This agent analyzes questions about soccer and determines the appropriate
    tool chain needed to answer them.
    """
    def __init__(self, model_name: str = DEFAULT_MODEL):
        """
        Initialize the Soccer Planning Agent.
        
        Args:
            model_name: The LLM model to use (default from config)
        """
        self.llm = ChatGoogleGenerativeAI(
            model=model_name, 
            temperature=MODEL_TEMPERATURE, 
            top_p=MODEL_TOP_P,
            max_output_tokens=MAX_COMPLETION_TOKENS #type: ignore
        )

        self.logger = logging.getLogger(f"{__name__}.{self.__class__.__name__}")
        self.planning_parser = PydanticOutputParser(pydantic_object=PlanningOutput)

        
        # Tool mapping dictionary using LangChain @tool decorated functions
        self.tool_registry: dict[str, Callable] = {
            "textual_entity_search": textual_entity_search,
            "textual_retrieval_augment": textual_retrieval_augment,
        }

        # List of all tools
        self.tools = list(self.tool_registry.values())
        
        self.graph = self._build_graph()
        self.logger.info(f"SoccerAgent initialized with model: {model_name}")
        self.logger.info(f"Loaded {len(self.tools)} LangChain tools")
        
    def _build_graph(self) -> CompiledStateGraph:
        """Build the LangGraph workflow."""
        # Create the graph
        workflow = StateGraph(AgentState)
        
        # Add nodes
        tool_node = ToolNode(self.tools, messages_key="tool_node_messages")
        workflow.add_node("tool_chain_planning", self._tool_chain_planning)
        workflow.add_node("execution_node", self._execution_node)
        workflow.add_node("tool_node", tool_node)

        # Define the flow
        workflow.set_entry_point("tool_chain_planning")
        workflow.add_edge("tool_chain_planning", "execution_node")
        workflow.add_conditional_edges(
            "execution_node",
            self.should_continue_call_tool,
            {
                "continue": "tool_node",
                "end": END
            }
        )
        workflow.add_edge("tool_node", "execution_node")
        
        return workflow.compile()
    
    def _tool_chain_planning(self, state: AgentState) -> AgentState:
        """
        This node is responsible for planning the tool chain to answer the user's query.
        
        Args:
            state: Current agent state
            
        Returns:
            Updated state with parsed known_info and tool_chain
        """
        self.logger.info("="*70)
        self.logger.info("🧠 Starting TOOL CHAIN PLANNING STEP")
        additional_material = state.get("additional_material", "None")
        if not additional_material or additional_material.strip() == "":
            additional_material = "None"
        
        # Build tool descriptions
        tool_descriptions = ""
        for tool in self.tools:
            tool_descriptions += f"- {tool.name}: {tool.description}\n"
        
        # Get format instructions
        format_instructions = self.planning_parser.get_format_instructions()
        
        planning_agent_prompt_template = get_planning_prompt_template()
        planning_agent_prompt = planning_agent_prompt_template.invoke({
            "toolbox_descriptions": tool_descriptions,
            "format_instructions": format_instructions,
            "user_query": state["user_query"],
            "additional_material": additional_material
        })

        # Get LLM response
        response = self.llm.invoke(planning_agent_prompt)
        logger.debug(f"Raw response from Planning Agent: {response}")
        response_text = response.content
        
        # Google Gemini models may not have reasoning_content in additional_kwargs
        if hasattr(response, 'additional_kwargs') and 'reasoning_content' in response.additional_kwargs:
            self.logger.info(f"LLM reasoning: {response.additional_kwargs['reasoning_content']}")
        
        # Parse with PydanticOutputParser
        planning_output: PlanningOutput = self.planning_parser.parse(response_text)
        
        self.logger.info("Tool Chain Planning Results:")
        self.logger.info(f"\t Known Info: {planning_output.known_info}")
        self.logger.info(f"\t Tool Chain: {planning_output.tool_chain}")
        self.logger.info("✅ TOOL CHAIN PLANNING STEP COMPLETED")
        self.logger.info("="*70)

        # Use structured output directly
        state["known_info"] = planning_output.known_info
        state["tool_chain"] = planning_output.tool_chain
        return state
    
    def _execution_node(self, state: AgentState) -> AgentState:
        """
        Iteratively execute the tool chain step by step using bind_tools with tool_choice.
        This allows the LLM to see the full tool schema and automatically generate correct parameters.
        
        Args:
            state: Current agent state with known_info and tool_chain
            
        Returns:
            Updated state with execution results
        """
        query = state["user_query"]
        additional_material = state.get("additional_material", "None")
        known_info = state["known_info"]
        tool_chain = state["tool_chain"]
        tool_calls_history = state.get("tool_calls_history", [])
        tool_results_history = state.get("tool_results_history", [])
        tool_node_messages = state.get("tool_node_messages", [])
        

        self.logger.info(f"🔧 Running TOOL EXECUTION STEP: Step {len(tool_calls_history)}/{len(tool_chain)+len(tool_calls_history)}")
        
         # If the previous step is from the tool_node, add the tool execution result to history and add the artifact to state
        if tool_node_messages:
            tool_result: ToolMessage = tool_node_messages[-1] # Each time only one tool is called, so the last message is the result of the current tool
            tool_results_history.append(tool_result)
            if tool_result.artifact:
                state["last_tool_artifact"] = tool_result.artifact
            self.logger.info(f"Received tool result: {tool_result.content}")
        
        
        if tool_chain:
            # Get current tool from chain and bind to LLM
            current_tool_name = tool_chain[0]
            tool_chain = tool_chain[1:]  # Remove current tool from chain
            current_tool = self.tool_registry.get(current_tool_name)
            if not current_tool:
                error_msg = f"Tool '{current_tool_name}' not found in registry. Available tools: {list(self.tool_registry.keys())}"
                raise ValueError(error_msg)
            model_with_tool = self.llm.bind_tools([current_tool])
            self.logger.info(f"Current Tool Name: {current_tool_name}")
            self.logger.debug(f"Current Tool Description: {current_tool.description}") # type: ignore

            # Build execution history string and prompt
            history_str = self._build_history_string(tool_calls_history, tool_results_history)
            execution_prompt_template = get_execution_prompt_template()
            execution_prompt = execution_prompt_template.invoke({
                "user_query": query,
                "additional_material": additional_material,
                "known_info": known_info,
                "tool_chain": " -> ".join(tool_chain),
                "history": history_str
            })

            try:
                # Invoke the model with the tool 
                response: AIMessage = model_with_tool.invoke(execution_prompt) # type: ignore
                self.logger.info(f"🤖 LLM Response: {response}")

                # Check if tool was called
                if not response.tool_calls or len(response.tool_calls) == 0:
                    error_msg = f"LLM did not generate a tool call for {current_tool_name}."
                    self.logger.error(error_msg)
                    raise Exception(error_msg)
                else:
                    # Add tool call message to tool_node_messages for the next tool_node
                    if tool_node_messages:
                        tool_node_messages.append(response)
                    else:
                        tool_node_messages = [response]

                    # Extract the tool call and add to tool calls history
                    tool_call: ToolCall = response.tool_calls[0]
                    tool_calls_history.append(tool_call)
                    self.logger.info(f"Tool Call Generated: {tool_call}")
                    
            except Exception as e:
                error_msg = f"Error executing tool: {str(e)}"
                self.logger.error(error_msg)
                raise Exception(error_msg)
        else:
            self.logger.info("No more tools to execute in the tool chain.")
            tool_node_messages = None  # No further tool calls
        
        state["tool_calls_history"] = tool_calls_history
        state["tool_results_history"] = tool_results_history
        state["tool_chain"] = tool_chain
        state["tool_node_messages"] = tool_node_messages
        self.logger.info("✅ TOOL EXECUTION STEP COMPLETED")
        self.logger.info("="*70)
        
        return state
    
    def should_continue_call_tool(self, state: AgentState):
        """
        Determine whether to continue calling tools or end execution.

        Args:
            state: Current agent state. If there are no tool call (tool_node_messages), we end execution.

        Returns:
            str: "continue" to keep calling tools, "end" to stop execution.
        """
        if state.get("tool_node_messages"):
            return "continue"
        else:
            return "end"
    
    def _build_history_string(self, tool_calls_history: List[ToolCall], tool_results_history: List[ToolMessage]) -> str:
        """
        Build the execution history string for the prompt.
        
        Args:
            tool_calls_history: List of tool calls
            tool_results_history: List of tool results
            
        Returns:
            str: Formatted history string
        """
        if not tool_calls_history and not tool_results_history:
            return "No execution history yet. This is the first step."
        
        history_parts = []

        # Integrate tool calls and results in order
        for i in range(len(tool_calls_history)):
            # Add tool call
            tool_call = tool_calls_history[i]
            tool_name = tool_call.get('name', 'unknown')
            args_items = tool_call.get('args', {})
            args_str = ", ".join(f"{arg}={value}" for arg, value in args_items.items())
            history_parts.append(f"<CALL_TOOL><TOOL_NAME>{tool_name}</TOOL_NAME><TOOL_ARGS>{args_str}</TOOL_ARGS></CALL_TOOL>")
            
            # Add corresponding tool result if available
            if i < len(tool_results_history):
                tool_result = tool_results_history[i]
                history_parts.append(f"<TOOL_RESULT>{tool_result.content}</TOOL_RESULT>")
        
        return "\n".join(history_parts)
    

    def run(self, user_query: str, additional_material: Optional[str] = None) -> dict:
        """
        Run the complete workflow: planning + execution.
        
        Args:
            user_query: The user's question about soccer
            additional_material: Optional additional context (e.g., image paths)
            
        Returns:
            Dictionary containing complete results from planning and execution
        """
        self.logger.info(f"Starting run for query: {user_query[:100]}...")
        
        # Initialize state
        initial_state = {
            "user_query": user_query,
            "additional_material": additional_material if additional_material else "None",
            "known_info": [],
            "tool_chain": [],
            "tool_calls_history": [],
            "tool_results_history": [],
            "tool_node_messages": [],
            "last_tool_artifact": None
        }
        
        # Run the full graph (planning → execution)
        final_state = self.graph.invoke(initial_state)
        
        # Prepare the complete results
        result = {
            "user_query": user_query,
            "known_info": final_state["known_info"],
            "tool_chain": final_state["tool_chain"],
            "planning_raw_response": final_state.get("planning_raw_response", ""),
            "tool_calls_history": final_state["tool_calls_history"],
            "tool_results_history": final_state["tool_results_history"],
            "tool_node_messages": final_state["tool_node_messages"],
            "last_tool_artifact": final_state.get("last_tool_artifact", None),
        }
        self.logger.info("Run completed successfully")
        return result["tool_results_history"][-1].content # TODO: Update to return LLM response when adding LLM tool


def main():
    """Example usage of the Soccer Planning Agent."""
    
    # Initialize the agent with Google Gemini model
    agent = SoccerAgent(model_name=DEFAULT_MODEL)
    
    # # Example 10:
    # logger.info("="*60)
    # logger.info("EXAMPLE 10")
    # logger.info("="*60)
    # query10 = "Which match had more total fouls: the 2018 Champions League final or the 2022 Champions League final?"
    # agent.run(query10)
    
    # # Example 11:
    # logger.info("="*60)
    # logger.info("EXAMPLE 11")
    # logger.info("="*60)
    # query11 = "Who scored the goal in the 2014 Champions League final, and what was the first professional club he ever played for?"
    # agent.run(query11)

    # Example 12:
    # logger.info("="*60)
    # logger.info("EXAMPLE 12")
    # logger.info("="*60)
    # query12 = "For the player in the image, in what stadium did he make his UEFA Champions League debut?"
    # additional_material12 = 'image": ["/path/to/player.jpg"]'
    # agent.run(query12, additional_material12)

    # Example 13: Test the chain textual_entity_search, texxtual_entity_augment
    logger.info("="*60)
    logger.info("EXAMPLE 12")
    logger.info("="*60)
    query13 = "Tell me about the golden period in Cristiano Ronaldo carrer"
    additional_material13 = None
    response = agent.run(query13, additional_material13)
    print(response)


if __name__ == "__main__":
    main()
