import logging
import uuid
from dotenv import load_dotenv
from typing import TypedDict, List, Optional, Callable
from pydantic import BaseModel, Field

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.messages import ToolMessage, ToolCall, AIMessage
from langgraph.graph import StateGraph, END
from langgraph.graph.state import CompiledStateGraph
from langgraph.prebuilt import ToolNode

from app.memory.chat_history import get_postgres_memory
from app.memory.conversation_memory import CustomSystemPromptMemory
from app.prompts.agent import get_planning_prompt_template, get_execution_prompt_template
from app.config.config import (
    DEFAULT_MODEL, GEMINI_2_5_FLASH, MODEL_TEMPERATURE, MODEL_TOP_P, MAX_COMPLETION_TOKENS,
    LOG_FORMAT, LOG_DATE_FORMAT, LOG_LEVEL
)
from app.toolbox import (
    textual_entity_search, 
    textual_retrieval_augment, 
    game_history_retrieval, 
    game_info_retrieval, 
    game_search, 
    choice_selection,
    entity_recognition,
    segment,
    frame_selection,
    commentary_generation,
)
from app.schema.chat import ChatRequest

# Load environment variables
load_dotenv()

# Configure logging
logger = logging.getLogger(__name__)


# Structured output models for LLM responses
class PlanningOutput(BaseModel):
    """Structured output for tool chain planning."""
    known_info: List[str] = Field(description="List of information items that are directly provided or known from the query")
    tool_chain: Optional[List[str]] = Field(default=None,description="Ordered list of tools needed to answer the query or None if no tools are needed")
    need_call_tools: Optional[bool] = Field(default=True, description="Indicates whether tool calls are necessary")

# Define the state structure for the agent
class AgentState(TypedDict):
    """State structure for the planning agent."""
    user_query: str # The user's soccer-related question
    additional_material: Optional[List[str]] # Additional material (e.g, image/video related to the user question)
    known_info: List[str] # This is generated by the planning step: Information known or provided directly. This is generated by the planning step.
    tool_chain: List[str] # This is generated by the planning step: The planned sequence of tools to execute. 
    tool_calls_history: List[ToolCall] # History of tool calls (requests to call a tool)
    tool_results_history: List[ToolMessage] # History of tool results (results of tool executions)
    tool_node_messages: List # Messages exchanged between execution_node and tool_node
    last_tool_artifact: Optional[str] # To store the tool's artifact output from the last tool call
    need_call_tools: Optional[bool] # Flag to indicate if more tools need to be called
    conversation_history: Optional[List[str]] # Optional conversation history for context


class SoccerAgent:
    """
    A LangGraph-based agent for planning soccer knowledge queries.
    
    This agent analyzes questions about soccer and determines the appropriate
    tool chain needed to answer them.
    """
    def __init__(self, model_name: str = DEFAULT_MODEL):
        """
        Initialize the Soccer Planning Agent.
        
        Args:
            model_name: The LLM model to use (default from config)
        """
        self.planning_llm = ChatGoogleGenerativeAI(
            model=model_name if model_name else GEMINI_2_5_FLASH, 
            temperature=MODEL_TEMPERATURE, 
            top_p=MODEL_TOP_P,
            max_output_tokens=MAX_COMPLETION_TOKENS,
            thinking_budget=3000,
            include_thoughts=True #type: ignore
        )
        self.execution_llm = ChatGoogleGenerativeAI(
            model=model_name if model_name else GEMINI_2_5_FLASH,
            temperature=MODEL_TEMPERATURE,
            top_p=MODEL_TOP_P,
            max_output_tokens=MAX_COMPLETION_TOKENS,
            thinking_budget=4000,
            include_thoughts=True #type: ignore
        )
        self.planning_parser = PydanticOutputParser(pydantic_object=PlanningOutput)

        
        # Tool mapping dictionary using LangChain @tool decorated functions
        self.tool_registry: dict[str, Callable] = {
            "textual_entity_search": textual_entity_search(),
            "textual_retrieval_augment": textual_retrieval_augment(),
            "game_search": game_search(),
            "game_history_retrieval": game_history_retrieval(),
            "game_info_retrieval": game_info_retrieval(),
            "entity_recognition": entity_recognition(),
            "choice_selection": choice_selection(),
            "segment": segment(),
            "frame_selection": frame_selection(),
            "commentary_generation": commentary_generation(),
        }

        # List of all tools
        self.tools = list(self.tool_registry.values())
        self.execution_llm_with_tools = self.execution_llm.bind_tools(self.tools) 
        
        self.graph = self._build_graph()
        logger.info(f"SoccerAgent initialized with model: {model_name}")
        logger.info(f"Loaded {len(self.tools)} LangChain tools")
        
    def _build_graph(self) -> CompiledStateGraph:
        """Build the LangGraph workflow."""
        # Create the graph
        workflow = StateGraph(AgentState)
        
        # Add nodes
        tool_node = ToolNode(self.tools, messages_key="tool_node_messages")
        workflow.add_node("tool_chain_planning", self._tool_chain_planning)
        workflow.add_node("execution_node", self._execution_node)
        workflow.add_node("tool_node", tool_node)

        # Define the flow
        workflow.set_entry_point("tool_chain_planning")
        workflow.add_edge("tool_chain_planning", "execution_node")
        workflow.add_conditional_edges(
            "execution_node",
            self.should_continue_call_tool,
            {
                "continue": "tool_node",
                "end": END
            }
        )
        workflow.add_edge("tool_node", "execution_node")
        
        return workflow.compile()
    
    def _tool_chain_planning(self, state: AgentState) -> AgentState:
        """
        This node is responsible for planning the tool chain to answer the user's query.
        
        Args:
            state: Current agent state
            
        Returns:
            Updated state with parsed known_info and tool_chain
        """
        logger.info("="*70)
        logger.info("🧠 Starting TOOL CHAIN PLANNING STEP")
        additional_material_list = state.get("additional_material")
        # Format List[str] to string for prompt
        additional_material = ", ".join(additional_material_list) if additional_material_list else "None"
        
        # Get conversation history from state
        conversation_history = state.get("conversation_history", "No previous conversation.")
        
        # Build tool descriptions
        tool_descriptions = ""
        for tool in self.tools:
            tool_descriptions += f"- {tool.name}: {tool.description}\n"
        
        # Get format instructions
        format_instructions = self.planning_parser.get_format_instructions()
        
        planning_agent_prompt_template = get_planning_prompt_template()
        planning_agent_prompt = planning_agent_prompt_template.invoke({
            "toolbox_descriptions": tool_descriptions,
            "format_instructions": format_instructions,
            "user_query": state["user_query"],
            "additional_material": additional_material,
            "conversation_history": conversation_history
        })

        # Get LLM response
        response = self.planning_llm.invoke(planning_agent_prompt)
        logger.debug(f"🤖 Response from Planning Agent: {response}")
        response_text = response.content[1] if isinstance(response.content, list) and len(response.content) > 1 else response.content # The content may contain thought signatures, so we extract the main response.
        
        # Parse with PydanticOutputParser
        planning_output: PlanningOutput = self.planning_parser.parse(response_text)
        
        logger.info("Tool Chain Planning Results:")
        logger.info(f"\t Known Info: {planning_output.known_info}")
        logger.info(f"\t Tool Chain: {planning_output.tool_chain}")
        logger.info("✅ TOOL CHAIN PLANNING STEP COMPLETED")
        logger.info("="*70)

        # Use structured output directly
        state["known_info"] = planning_output.known_info
        state["tool_chain"] = planning_output.tool_chain
        return state
    
    def _execution_node(self, state: AgentState) -> AgentState:
        """
        Iteratively execute the tool chain step by step using bind_tools with tool_choice.
        This allows the LLM to see the full tool schema and automatically generate correct parameters.
        
        Args:
            state: Current agent state with known_info and tool_chain
            
        Returns:
            Updated state with execution results
        """
        query = state["user_query"]
        additional_material_list = state.get("additional_material", [])
        known_info = state["known_info"]
        tool_chain = state["tool_chain"]
        tool_calls_history = state.get("tool_calls_history", [])
        tool_results_history = state.get("tool_results_history", [])
        tool_node_messages = state.get("tool_node_messages", [])
        conversation_history = state.get("conversation_history", "No previous conversation.")
        

        logger.info(f"🔧 Running TOOL EXECUTION STEP: Step {len(tool_calls_history)}")
        
         # If the previous step is from the tool_node, add the tool execution result to history and add the artifact to state
        if tool_node_messages:
            tool_result: ToolMessage = tool_node_messages[-1] # Each time only one tool is called, so the last message is the result of the current tool
            tool_results_history.append(tool_result)
            state["last_tool_artifact"] = tool_result.artifact if hasattr(tool_result, 'artifact') else None
            logger.info(f"Received tool result: {tool_result.content}")
        
        # Format List[str] to string for prompt
        additional_material_str = ", ".join(additional_material_list) if additional_material_list else "None"
        
        # Build execution history string and prompt
        history_str = self._build_history_string(tool_calls_history, tool_results_history)
        
        # Check if we're on the last tool (all tools have been executed)
        is_last_tool = len(tool_calls_history) >= len(tool_chain) if tool_chain else True
        conversation_history_for_prompt = conversation_history if is_last_tool else "Not applicable yet (still executing tool chain)."
        
        execution_prompt_template = get_execution_prompt_template()
        execution_prompt = execution_prompt_template.invoke({
            "user_query": query,
            "additional_material": additional_material_str,
            "conversation_history": conversation_history_for_prompt,
            "known_info": known_info,
            "tool_chain": " -> ".join(tool_chain) if tool_chain else "No tools needed",
            "history": history_str,
            
        })
        
        logger.info(f"Tool chain to execute: {' -> '.join(tool_chain) if tool_chain else 'No tools needed'}")


        try:
            # Invoke the model with the tool 
            response: AIMessage = self.execution_llm_with_tools.invoke(execution_prompt) # type: ignore
            logger.info(f"🤖 Response from execution agent: \n \t Response content: {response.text} \n \t Tool Calls: {response.tool_calls}")
            tool_node_messages = [response] # Add the message to tool_node_messages for tool_node if there is no tool call the should_or_continue node will end execution
            
            if response.tool_calls:
                # Extract the tool call and add to tool calls history
                tool_call: ToolCall = response.tool_calls[0]
                tool_calls_history.append(tool_call)
                logger.info(f"Added ToolCall to history. Executed total: {len(tool_calls_history)}")
            else:
                logger.info("No tool call made by the execution agent. Ending execution.")
    
        except Exception as e:
            error_msg = f"Error in tool execution agent: {str(e)}"
            logger.error(error_msg)
            logger.info("Stopping execution due to error.")
            tool_node_messages = [AIMessage(content="The execution has been stopped due to an error. Please try again later.")]
        
        # Update state
        state['additional_material'] = additional_material_list
        state["tool_calls_history"] = tool_calls_history
        state["tool_results_history"] = tool_results_history
        state["tool_chain"] = tool_chain
        state["tool_node_messages"] = tool_node_messages
        logger.info("✅ TOOL EXECUTION STEP COMPLETED")
        logger.info("="*70)
        
        return state
    
    def should_continue_call_tool(self, state: AgentState):
        """
        Determine whether to continue calling tools or end execution.

        Args:
            state: Current agent state. If there are no tool call (tool_node_messages), we end execution.

        Returns:
            str: "continue" to keep calling tools, "end" to stop execution.
        """
        tool_node_messages = state.get("tool_node_messages")
        last_message = tool_node_messages[-1] if len(tool_node_messages) > 0 else None
        if not last_message or not last_message.tool_calls:
            return "end"
        else:
            return "continue"
    
    def _build_history_string(self, tool_calls_history: List[ToolCall], tool_results_history: List[ToolMessage]) -> str:
        """
        Build the execution history string for the prompt.
        
        Args:
            tool_calls_history: List of tool calls
            tool_results_history: List of tool results
            
        Returns:
            str: Formatted history string
        """
        if not tool_calls_history and not tool_results_history:
            return "No execution history yet. This is the first step."
        
        history_parts = []

        # Integrate tool calls and results in order
        for i in range(len(tool_calls_history)):
            # Add tool call
            tool_call = tool_calls_history[i]
            tool_name = tool_call.get('name', 'unknown')
            args_items = tool_call.get('args', {})
            args_str = ", ".join(f"{arg}={value}" for arg, value in args_items.items())
            history_parts.append(f"<CALL_TOOL><TOOL_NAME>{tool_name}</TOOL_NAME><TOOL_ARGS>{args_str}</TOOL_ARGS></CALL_TOOL>")
            
            # Add corresponding tool result if available
            if i < len(tool_results_history):
                tool_result = tool_results_history[i]
                history_parts.append(f"<TOOL_RESULT>{tool_result.content}</TOOL_RESULT>")
        
        return "\n".join(history_parts)
    
    async def get_memory(self, session_id: str):
        """
        Get conversation memory for the given session.
        
        Args:
            session_id: Session ID to retrieve memory for
            
        Returns:
            Tuple of (memory_object, connection, pool) for cleanup
        """
        memory, connection, pool = get_postgres_memory(session_id)
        memory_object = CustomSystemPromptMemory(
            memory_key="history",
            chat_memory=memory.chat_memory,
            return_messages=True,
            max_history=15,  # Limit to last 15 messages
        )
        return memory_object, connection, pool
    async def cleanup(self, connection, pool, session_id: str):
        """
        Cleanup database connection and return to pool.
        
        Args:
            connection: Database connection to cleanup
            pool: Connection pool to return connection to
            session_id: Session ID for logging
        """
        try:
            if not connection:
                return

            # Try to commit any pending transactions
            try:
                closed = getattr(connection, "closed", False)
                if not closed:
                    connection.commit()
            except Exception:
                # Best-effort commit; ignore errors here
                pass

            # Return connection to pool if available, otherwise close it
            if pool:
                try:
                    pool.putconn(connection)
                    logging.debug(f"Connection returned to pool for session {session_id}")
                except Exception:
                    try:
                        connection.close()
                    except Exception:
                        pass
            else:
                try:
                    connection.close()
                except Exception:
                    pass
        except Exception as e:
            logging.error(f"Cleanup error: {e}")
            try:
                if connection:
                    connection.close()
            except Exception:
                pass

    async def run(self, request: ChatRequest) -> str:
        """
        Run the complete workflow: planning + execution.
        
        Args:
            request: The ChatRequest object containing user_query and additional_material
            
        Returns:
            Dictionary containing complete results from planning and execution
        """
        try:
            logger.info(f"Starting run for query: {request.user_query[:100]}...")
            # Initialize memory variables
            connection = None
            pool = None
            memory_object = None
            chat_history = None
            session_id = str(uuid.uuid5(uuid.NAMESPACE_DNS, request.user_id))

            # Load conversation history if session_id provided
            if session_id:
                try:
                    memory_object, connection, pool = await self.get_memory(session_id=session_id)
                    try:
                        history = memory_object.load_memory_variables({})
                        chat_history = history.get("history")
                    except Exception as e:
                        logging.warning(f"Memory load failed for session {session_id}: {e}")
                        chat_history = None
                except Exception as e:
                    logging.warning(f"Failed to obtain memory for session {session_id}: {e}")
                    memory_object = None

            # Format conversation history into string
            history_text = ""
            if chat_history:
                history_text = "\n\n### LỊCH SỬ HỘI THOẠI:\n"
                for msg in chat_history[-10:]:  # Last 10 messages only
                    if hasattr(msg, 'content'):
                        role = "User" if msg.__class__.__name__ == "HumanMessage" else "Assistant"
                        history_text += f"{role}: {msg.content}\n"
            logger.info(f"-----------------------------------history: {history_text} .")
            # Initialize state
            initial_state = {
                "user_query": request.user_query,
                "additional_material": request.additional_material or [],
                "known_info": [],
                "tool_chain": [],
                "tool_calls_history": [],
                "tool_results_history": [],
                "tool_node_messages": [],
                "last_tool_artifact": None,
                "conversation_history": history_text,
                "need_call_tools": True
            }
            
            # Run the full graph (planning → execution)
            final_state = await self.graph.ainvoke(initial_state)
            
            # Prepare the complete results
            result = {
                "user_query": request.user_query,
                "known_info": final_state["known_info"],
                "tool_chain": final_state["tool_chain"],
                "planning_raw_response": final_state.get("planning_raw_response", ""),
                "tool_calls_history": final_state["tool_calls_history"],
                "tool_results_history": final_state["tool_results_history"],
                "tool_node_messages": final_state["tool_node_messages"],
                "last_tool_artifact": final_state.get("last_tool_artifact", None),
            }
            logger.info("Run completed successfully")
            if memory_object:
                try:
                    # Extract the final response text from tool_node_messages
                    final_response = final_state["tool_node_messages"][-1].text if final_state["tool_node_messages"] else "No response generated"
                    memory_object.save_context(
                        inputs={"input": request.user_query},  # Save original query, not formatted prompt
                        outputs={"output": final_response}  # Save the final response as string, not the list of ToolMessage objects
                    )
                except Exception as e:
                    logging.warning(f"Failed to save memory for session {session_id}: {e}")

            logging.info("\n✓ Data description created successfully!\n")

        except Exception as e:
            logging.error(f"Error describing DataFrame: {e}", exc_info=True)
            return "✗ Unable to create description for this data."
        finally:
            # Always cleanup connection
            try:
                self.cleanup(connection=connection, pool=pool, session_id=session_id)
                logging.debug("✅ ChatAgent connection cleaned up")
            except Exception as cleanup_error:
                logging.error(f"❌ ChatAgent cleanup error: {cleanup_error}")        

        # Return the final response content from execution agent. That is the generated answer to user query based on all tool calls.
        return result["tool_node_messages"][-1].text # Using .text ínstead of .content for AIMessage because Gemini 3 series models will always return a list of content blocks to capture thought signatures.

# Do NOT create singleton here - it will be created in main.py lifespan
# agent_service = SoccerAgent()

def get_agent_service() -> SoccerAgent:
    """Get the singleton SoccerAgent service from main.py."""
    import main
    if main.agent_service is None:
        raise RuntimeError("SoccerAgent not initialized. This should not happen if lifespan is working correctly.")
    return main.agent_service